// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAanSBz2c6t52tlLGFaOJ3L6ynSCm2TdYg',
    appId: '1:352473030604:web:6cbddb2b621b0842ff4769',
    messagingSenderId: '352473030604',
    projectId: 'plantsense-9b85f',
    authDomain: 'plantsense-9b85f.firebaseapp.com',
    storageBucket: 'plantsense-9b85f.firebasestorage.app',
    measurementId: 'G-02Z76N3F5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAykkBnnsoLO0fgOVvjtkruej9K2GPtcgo',
    appId: '1:352473030604:android:713c965540fbf749ff4769',
    messagingSenderId: '352473030604',
    projectId: 'plantsense-9b85f',
    storageBucket: 'plantsense-9b85f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU3sWotDRz2bTKgubMHtQ7_nsmOZU5k2k',
    appId: '1:352473030604:ios:736e1307f9a62685ff4769',
    messagingSenderId: '352473030604',
    projectId: 'plantsense-9b85f',
    storageBucket: 'plantsense-9b85f.firebasestorage.app',
    iosBundleId: 'com.example.plantSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU3sWotDRz2bTKgubMHtQ7_nsmOZU5k2k',
    appId: '1:352473030604:ios:736e1307f9a62685ff4769',
    messagingSenderId: '352473030604',
    projectId: 'plantsense-9b85f',
    storageBucket: 'plantsense-9b85f.firebasestorage.app',
    iosBundleId: 'com.example.plantSense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAanSBz2c6t52tlLGFaOJ3L6ynSCm2TdYg',
    appId: '1:352473030604:web:f3020693a84563ebff4769',
    messagingSenderId: '352473030604',
    projectId: 'plantsense-9b85f',
    authDomain: 'plantsense-9b85f.firebaseapp.com',
    storageBucket: 'plantsense-9b85f.firebasestorage.app',
    measurementId: 'G-H11RRMD6NQ',
  );
}
